---
language: python

services: docker

os: linux
dist: bionic

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install sshpass

  # Install Docker for Python
  - pip install docker

  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  - cd tests && make

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
